#!/bin/bash

i3status | while :
do
        read line
        bright=$(</sys/class/backlight/intel_backlight/brightness)
        percent_bright=$(bc <<< "scale=1;$bright / 937")
        echo "$percent_bright | $line" || exit 1
done
